# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-06 01:32
from __future__ import unicode_literals

import apps.core.models
from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('function', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
                ('avatar_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=apps.core.models.Band.image_path)),
            ],
            options={
                'verbose_name_plural': 'Banda',
                'verbose_name': 'Banda',
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('localization', models.CharField(max_length=400)),
                ('cartaz_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=apps.core.models.Concert.image_path)),
            ],
            options={
                'verbose_name_plural': 'Agenda',
                'verbose_name': 'Agenda',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('news_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=apps.core.models.News.image_path)),
            ],
            options={
                'verbose_name_plural': 'Notícias',
                'verbose_name': 'Notícia',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vídeos',
                'verbose_name': 'Video',
            },
        ),
    ]
